export const dgroup = [{
        id: "group1",
        name: "Dessert Debate",
        avatar: "DD",
        description: "Chef Alex & 31 others",
        members: 32,
        lastMessage: "Great choice 🍰",
        lastActivity: "5 min ago",
      },
      {
        id: "group2",
        name: "Architecture Club",
        avatar: "AC",
        description: "Ted & 15 others",
        members: 16,
        lastMessage: "Check out this new design!",
        lastActivity: "2 hours ago",
      },
      {
        id: "group3",
        name: "Legal Team",
        avatar: "LT",
        description: "Marshall & 8 others",
        members: 9,
        lastMessage: "Meeting at 3pm tomorrow",
        lastActivity: "Yesterday",
      },
      {
        id: "group4",
        name: "Art Enthusiasts",
        avatar: "AE",
        description: "Lily & 24 others",
        members: 25,
        lastMessage: "New exhibition this weekend!",
        lastActivity: "2 days ago",
      },
      {
        id: "group5",
        name: "News Anchors",
        avatar: "NA",
        description: "Robin & 12 others",
        members: 13,
        lastMessage: "Breaking news: We're awesome!",
        lastActivity: "3 days ago",
      },
      {
        id: "group6",
        name: "Coffee Lovers",
        avatar: "CL",
        description: "Barista Joe & 18 others",
        members: 19,
        lastMessage: "Anyone tried the new blend?",
        lastActivity: "4 days ago",
      },
      {
        id: "group7",
        name: "Book Club",
        avatar: "BC",
        description: "Emily & 12 others",
        members: 13,
        lastMessage: "Next book: The Great Gatsby",
        lastActivity: "5 days ago",
      },
      {
        id: "group8",
        name: "Fitness Fanatics",
        avatar: "FF",
        description: "Trainer Mike & 22 others",
        members: 23,
        lastMessage: "New workout routine posted!",
        lastActivity: "1 week ago",
      },
      {
        id: "group9",
        name: "Travel Buddies",
        avatar: "TB",
        description: "Sarah & 30 others",
        members: 31,
        lastMessage: "Planning trip to Bali next month",
        lastActivity: "2 weeks ago",
      },
      {
        id: "group10",
        name: "Tech Talk",
        avatar: "TT",
        description: "Developer Dan & 45 others",
        members: 46,
        lastMessage: "Did you see the new AI features?",
        lastActivity: "3 weeks ago",
      }];


export const dstatus = [
      {
        id: "status1",
        userId: "user1",
        userName: "Ted Mosby",
        userInitials: "TM",
        content: "Working on a new building design! 🏢",
        timestamp: "2 hours ago",
        viewed: false,
      },
      {
        id: "status2",
        userId: "user2",
        userName: "Barney Stinson",
        userInitials: "BS",
        content: "Suit up! 👔",
        timestamp: "4 hours ago",
        viewed: false,
      },
      {
        id: "status3",
        userId: "user3",
        userName: "Marshall Erikson",
        userInitials: "ME",
        content: "Just won another case! ⚖️",
        timestamp: "6 hours ago",
        viewed: true,
      },
      {
        id: "status4",
        userId: "user4",
        userName: "Lily Aldrin",
        userInitials: "LA",
        content: "New art project coming soon! 🎨",
        timestamp: "8 hours ago",
        viewed: true,
      },
      {
        id: "status5",
        userId: "user5",
        userName: "Robin Scherbatsky",
        userInitials: "RS",
        content: "Live from New York! 📺",
        timestamp: "10 hours ago",
        viewed: false,
      },
    ]